#!/usr/bin/env python3
"""
E2E tests for the generator: documentary create → progress → video, AI-clips, and generator APIs.
Uses Flask test client (no live server). Run from project root: python scripts/test_generator_e2e.py
"""
import os
import sys
import time
import json

_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _root)
os.chdir(_root)

try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(_root, '.env'))
except Exception:
    pass


def get_client():
    """Create Flask app and return test client. Uses app_context so DB access works."""
    from src.app import create_app
    app = create_app()
    app.config['TESTING'] = True
    client = app.test_client()
    # Keep app and push context so generator_db_service can access db during requests
    client._app = app
    return client


def _get(path, client):
    r = client.get(path)
    try:
        return r.status_code, r.get_json() if r.content_type and 'json' in r.content_type else None
    except Exception:
        return r.status_code, None


def _post(path, client, data=None):
    r = client.post(path, data=json.dumps(data or {}), content_type='application/json')
    try:
        return r.status_code, r.get_json() if r.content_type and 'json' in r.content_type else None
    except Exception:
        return r.status_code, None


def test_generator_health(client):
    """GET /api/generator/test"""
    code, data = _get('/api/generator/test', client)
    if code != 200:
        return False, f"Expected 200, got {code}"
    if not data or not data.get('success'):
        return False, f"success not true: {data}"
    if 'database_available' not in data or 'video_pipeline_available' not in data:
        return False, f"Missing keys: {data}"
    return True, None


def test_generator_history(client):
    """GET /api/generator/history"""
    code, data = _get('/api/generator/history?user_id=test_user&limit=10', client)
    if code != 200:
        return False, f"Expected 200, got {code}"
    if not data or not data.get('success'):
        return False, f"success not true: {data}"
    if 'history' not in data:
        return False, f"Missing history: {data}"
    h = data['history']
    if not isinstance(h, dict) or 'recent' not in h:
        return False, f"history should have total/recent: {h}"
    return True, None


def test_generator_statistics(client):
    """GET /api/generator/statistics"""
    code, data = _get('/api/generator/statistics?user_id=test_user', client)
    if code != 200:
        return False, f"Expected 200, got {code}"
    if not data or not data.get('success'):
        return False, f"success not true: {data}"
    if 'statistics' not in data:
        return False, f"Missing statistics: {data}"
    return True, None


def test_generator_performance(client):
    """GET /api/generator/performance"""
    code, data = _get('/api/generator/performance?user_id=test_user', client)
    if code != 200:
        return False, f"Expected 200, got {code}"
    if not data or not data.get('success'):
        return False, f"success not true: {data}"
    if 'performance' not in data:
        return False, f"Missing performance: {data}"
    return True, None


def test_generator_jobs_list(client):
    """GET /api/generator/jobs"""
    code, data = _get('/api/generator/jobs?limit=5', client)
    if code != 200:
        return False, f"Expected 200, got {code}"
    if not data or not data.get('success'):
        return False, f"success not true: {data}"
    if 'jobs' not in data:
        return False, f"Missing jobs: {data}"
    return True, None


def test_documentary_create_progress_video(client, poll_seconds=60, poll_interval=1.5):
    """
    POST /api/generator/create → poll /api/documentary/progress/<id> until completed/failed
    → GET /api/documentary/video/<id>. Verifies error_message on failure.
    """
    code, data = _post('/api/generator/create', client, {
        'title': 'E2E Test Documentary',
        'description': 'Generated by test_generator_e2e',
        'user_id': 'test_user',
    })
    if code not in (200, 201, 202):
        return False, f"Create returned {code}: {data}"
    if not data or not data.get('success'):
        return False, f"Create success false: {data}"
    doc_id = data.get('documentary_id')
    if not doc_id:
        return False, f"No documentary_id: {data}"

    deadline = time.monotonic() + poll_seconds
    last_status = None
    while time.monotonic() < deadline:
        code, prog = _get(f'/api/documentary/progress/{doc_id}', client)
        if code != 200:
            return False, f"Progress returned {code}: {prog}"
        if not prog or not prog.get('success'):
            return False, f"Progress success false: {prog}"
        last_status = prog.get('status')
        if last_status == 'completed':
            video_url = prog.get('video_url')
            if not video_url:
                return False, "completed but no video_url in progress"
            code2, vid = _get(f'/api/documentary/video/{doc_id}', client)
            if code2 != 200:
                return False, f"Video endpoint returned {code2}"
            if vid and vid.get('status') == 'completed':
                return True, None
            if client.get(f'/api/documentary/video/{doc_id}').status_code == 200:
                return True, None
            return True, None
        if last_status in ('failed', 'error'):
            err = prog.get('error_message') or prog.get('message')
            if err:
                return True, None
            return False, f"Job failed but no error_message: {prog}"
        time.sleep(poll_interval)

    return False, f"Timeout after {poll_seconds}s; last status: {last_status}"


def test_ai_clips_create_and_status(client):
    """POST /api/ai-clips/generate → GET /api/generator/ai-clips/<job_id>"""
    code, data = _post('/api/ai-clips/generate', client, {
        'prompt': 'E2E test clips',
        'user_id': 'test_user',
        'clip_count': 2,
        'duration': 5,
    })
    if code not in (200, 201, 202):
        return False, f"AI-clips create returned {code}: {data}"
    if not data or not data.get('success'):
        return False, f"AI-clips success false: {data}"
    job_id = data.get('job_id')
    if not job_id:
        return False, f"No job_id: {data}"

    code2, status_data = _get(f'/api/generator/ai-clips/{job_id}', client)
    if code2 != 200:
        return False, f"AI-clips status returned {code2}: {status_data}"
    if not status_data or not status_data.get('success'):
        return False, f"AI-clips status success false: {status_data}"
    if 'status' not in status_data:
        return False, f"Missing status: {status_data}"
    return True, None


def test_unified_generate_video(client):
    """POST /api/unified/generate-video returns 202 and documentary_id."""
    code, data = _post('/api/unified/generate-video', client, {
        'prompt': 'Unified E2E test',
        'user_id': 'test_user',
    })
    if code not in (200, 201, 202):
        return False, f"Unified create returned {code}: {data}"
    if not data or not data.get('success'):
        return False, f"Unified success false: {data}"
    if not data.get('documentary_id') and not data.get('video_id'):
        return False, f"No documentary_id/video_id: {data}"
    return True, None


def main():
    import argparse
    p = argparse.ArgumentParser(description="Generator E2E tests")
    p.add_argument("--quick", action="store_true", help="Skip documentary create→progress→video (faster)")
    p.add_argument("--poll", type=int, default=60, metavar="SEC", help="Max seconds to poll for documentary completion (default 60)")
    args = p.parse_args()

    print("Generator E2E tests (Flask test client)")
    if args.quick:
        print("(quick mode: skipping documentary poll)")
    print("=" * 60)
    try:
        client = get_client()
    except Exception as e:
        print(f"FAIL: Could not create test client: {e}")
        import traceback
        traceback.print_exc()
        return 1
    # Reset generator engine before testing so tests start from a clean state
    try:
        r = client.get('/api/generator/reset-for-test?confirm=test')
        if r.status_code == 200:
            data = r.get_json() if r.content_type and 'json' in (r.content_type or '') else {}
            if data and data.get('success'):
                print("  [OK] Generator engine reset (in-memory jobs cleared)")
    except Exception as e:
        print("  [--] Reset failed:", e, "(continuing anyway)")

    tests = [
        ("Generator health (test)", test_generator_health),
        ("Generator jobs list", test_generator_jobs_list),
        ("Generator history", test_generator_history),
        ("Generator statistics", test_generator_statistics),
        ("Generator performance", test_generator_performance),
        ("Unified generate-video (create only)", test_unified_generate_video),
        ("AI-clips create + status", test_ai_clips_create_and_status),
    ]
    if not args.quick:
        tests.append(("Documentary create → progress → video", lambda c: test_documentary_create_progress_video(c, poll_seconds=args.poll)))
    passed = 0
    failed = []
    for name, fn in tests:
        try:
            ok, err = fn(client)
            if ok:
                print(f"  OK   {name}")
                passed += 1
            else:
                print(f"  FAIL {name}: {err}")
                failed.append((name, err))
        except Exception as e:
            print(f"  ERROR {name}: {e}")
            import traceback
            traceback.print_exc()
            failed.append((name, str(e)))

    print("=" * 60)
    print(f"Result: {passed}/{len(tests)} passed")
    if failed:
        print("\nFailed:")
        for name, err in failed:
            print(f"  - {name}: {err}")
        return 1
    print("\nAll generator E2E tests passed.")
    return 0


if __name__ == '__main__':
    sys.exit(main())
